Traceback (most recent call last):
  File "build_frustum_dataset.py", line 104, in <module>
    main(args)
  File "build_frustum_dataset.py", line 83, in main
    create_frustum_data(dataset,New_Directory, args.frustum_method, args.viz)
  File "build_frustum_dataset.py", line 61, in create_frustum_data
    dict_list.append(run.get_point_cloud_log(frustum, boxes=None, key=frustum_labels[pc]))
  File "/Users/stephennelson/Projects/Learning-Frustum-Proposals/wandb_utils/wandb.py", line 156, in get_point_cloud_log
    pc_dict = {
TypeError: unhashable type: 'list'