2022-12-27 22:34:09,311 INFO    MainThread:23649 [wandb_setup.py:_flush():75] Loading settings from /Users/stephennelson/.config/wandb/settings
2022-12-27 22:34:09,311 INFO    MainThread:23649 [wandb_setup.py:_flush():75] Loading settings from /Users/stephennelson/Projects/Learning-Frustum-Proposals/preprocess/wandb/settings
2022-12-27 22:34:09,311 INFO    MainThread:23649 [wandb_setup.py:_flush():75] Loading settings from environment variables: {}
2022-12-27 22:34:09,312 INFO    MainThread:23649 [wandb_setup.py:_flush():75] Inferring run settings from compute environment: {'program_relpath': 'preprocess/build_frustum_dataset.py', 'program': 'build_frustum_dataset.py'}
2022-12-27 22:34:09,312 INFO    MainThread:23649 [wandb_init.py:_log_setup():438] Logging user logs to /Users/stephennelson/Projects/Learning-Frustum-Proposals/preprocess/wandb/run-20221227_223409-2f2ff59t/logs/debug.log
2022-12-27 22:34:09,312 INFO    MainThread:23649 [wandb_init.py:_log_setup():439] Logging internal logs to /Users/stephennelson/Projects/Learning-Frustum-Proposals/preprocess/wandb/run-20221227_223409-2f2ff59t/logs/debug-internal.log
2022-12-27 22:34:09,312 INFO    MainThread:23649 [wandb_init.py:init():472] calling init triggers
2022-12-27 22:34:09,312 INFO    MainThread:23649 [wandb_init.py:init():475] wandb.init called with sweep_config: {}
config: {}
2022-12-27 22:34:09,313 INFO    MainThread:23649 [wandb_init.py:init():525] starting backend
2022-12-27 22:34:09,313 INFO    MainThread:23649 [backend.py:_multiprocessing_setup():99] multiprocessing start_methods=spawn,fork,forkserver, using: spawn
2022-12-27 22:34:09,341 INFO    MainThread:23649 [backend.py:ensure_launched():219] starting backend process...
2022-12-27 22:34:09,352 INFO    MainThread:23649 [backend.py:ensure_launched():224] started backend process with pid: 23660
2022-12-27 22:34:09,353 INFO    MainThread:23649 [wandb_init.py:init():534] backend started and connected
2022-12-27 22:34:09,361 INFO    MainThread:23649 [wandb_init.py:init():598] updated telemetry
2022-12-27 22:34:09,396 INFO    MainThread:23649 [wandb_init.py:init():629] communicating run to backend with 30 second timeout
2022-12-27 22:34:13,581 ERROR   Thread-1  :23649 [internal_api.py:execute():144] 500 response executing GraphQL.
2022-12-27 22:34:13,582 ERROR   Thread-1  :23649 [internal_api.py:execute():145] {"error":"internal database error"}
2022-12-27 22:34:22,154 ERROR   Thread-1  :23649 [internal_api.py:execute():144] 500 response executing GraphQL.
2022-12-27 22:34:22,154 ERROR   Thread-1  :23649 [internal_api.py:execute():145] {"error":"internal database error"}
2022-12-27 22:34:39,402 INFO    MainThread:23649 [interface_shared.py:_communicate_run():325] couldn't get run from backend
2022-12-27 22:34:39,405 ERROR   MainThread:23649 [wandb_init.py:init():634] backend process timed out
2022-12-27 22:34:39,405 ERROR   MainThread:23649 [wandb_init.py:init():645] encountered error: Error communicating with wandb process
try: wandb.init(settings=wandb.Settings(start_method='fork'))
or:  wandb.init(settings=wandb.Settings(start_method='thread'))
For more info see: https://docs.wandb.ai/library/init#init-start-error
2022-12-27 23:48:27,574 INFO    MainThread:23649 [wandb_init.py:teardown():286] tearing down wandb.init
