Traceback (most recent call last):
  File "plot_gt_kitti.py", line 72, in <module>
    main(args)
  File "plot_gt_kitti.py", line 40, in main
    with open(kitti_label) as label_file:
FileNotFoundError: [Errno 2] No such file or directory: '/Users/stephennelson/Projects/Data/Kitti/training/label_2/000142.bin'